### ISSUE TITLE
Later versions missing Prioritise take item from inventory config

### ISSUE THREAD

**Issue by VirtueAvatar** [abearcodes/Valheim#22] opened 2021-03-07 05:05 UTC
In one of the earlier versions (1.0.3?) there was a section in the config that included this:

```
## Prioritize taking items from the players inventory when crafting
# Setting type: Boolean
# Default value: false
TakeFromPlayerInventoryFirst = false
```

It seems this functionality is gone from the mod. Can it be returned?

**Comment by abearcodes** [comment] 2021-03-07 10:21
@VirtueAvatar the option `TakeFromPlayerInventoryFirst` is there again as of 1.0.8, with a bugfix that fixes item double item removal if disabled in 1.0.9 (the one discussed in #21)

Duplicate of #18, closing. If you have any additional questions, feel free to re-open!

**Closed by abearcodes** 2021-03-07 10:21 UTC
